import Config

# MinIO / S3-compatible object storage
config :ex_aws,
  access_key_id: System.get_env("MINIO_ACCESS_KEY", "minio"),
  secret_access_key: System.get_env("MINIO_SECRET_KEY", "minio123"),
  region: System.get_env("MINIO_REGION", "us-east-1")

config :ex_aws, :s3,
  scheme: "http://",
  host: System.get_env("MINIO_HOST", "localhost"),
  port: String.to_integer(System.get_env("MINIO_PORT", "9000")),
  virtual_host: false

config :sqlete, :storage_bucket, System.get_env("STORAGE_BUCKET", "sqlete-pdfs")

# Configure your database
config :sqlete, SQLete.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "sqlete_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sqlete, SQLeteWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "GDS6uFzEYJNiuvoDlH7zOkH9Lv65hF+ChwfukY6hCSpfHpk7CI3wR4YuVZHhl+e6",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sqlete, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sqlete, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :sqlete, SQLeteWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/sqlete_web/router\.ex$",
      ~r"lib/sqlete_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :sqlete, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
