import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sqlete, SQLeteWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# NOTE: `force_ssl` is intentionally disabled for the hackathon deploy, where the
# app is served over plain HTTP by IP (no TLS / reverse proxy). Re-enable it once a
# domain + HTTPS is in place. `:force_ssl` must be set at compile-time.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
